# Generated by Django 6.0.7 on 2026-07-20 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeveloperCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('skills', models.ManyToManyField(related_name='developers', to='api.skilltag')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
                ('min_experience_required', models.IntegerField(default=0)),
                ('required_tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='api.skilltag')),
            ],
        ),
    ]
