# Generated by Django 6.0.7 on 2026-07-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyclient',
            name='max_budget_lpa',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='developercandidate',
            name='average_tenure_months',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='developercandidate',
            name='expected_salary_lpa',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='developercandidate',
            name='notice_period_days',
            field=models.IntegerField(default=0),
        ),
    ]
