# Generated by Django 6.0.7 on 2026-07-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_companyclient_max_budget_lpa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developercandidate',
            name='average_tenure_months',
        ),
        migrations.AddField(
            model_name='developercandidate',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
