# Generated by Django 6.0.7 on 2026-07-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_developercandidate_average_tenure_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyclient',
            name='required_tech',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='developercandidate',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='companyclient',
            name='max_budget_lpa',
        ),
        migrations.RemoveField(
            model_name='companyclient',
            name='min_experience_required',
        ),
        migrations.RemoveField(
            model_name='developercandidate',
            name='expected_salary_lpa',
        ),
        migrations.RemoveField(
            model_name='developercandidate',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='developercandidate',
            name='notice_period_days',
        ),
        migrations.RemoveField(
            model_name='developercandidate',
            name='score',
        ),
        migrations.AddField(
            model_name='companyclient',
            name='max_budget_lps',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='developercandidate',
            name='expected_salary_lps',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='developercandidate',
            name='status',
            field=models.CharField(default='Applied', max_length=50),
        ),
        migrations.AlterField(
            model_name='developercandidate',
            name='experience_years',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='SkillTag',
        ),
        migrations.AddField(
            model_name='developercandidate',
            name='skills',
            field=models.TextField(default='Python', help_text='Comma-separated skills'),
            preserve_default=False,
        ),
    ]
