# Generated by Django 6.0.7 on 2026-07-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_companyclient_required_tech_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyclient',
            name='min_experience_years',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='developercandidate',
            name='previous_companies',
            field=models.TextField(blank=True, help_text='Comma-separated company names'),
        ),
        migrations.AddField(
            model_name='developercandidate',
            name='projects_summary',
            field=models.TextField(blank=True, help_text='Brief about projects'),
        ),
        migrations.AddField(
            model_name='developercandidate',
            name='qualification',
            field=models.CharField(default='B.Tech / Graduate', max_length=150),
        ),
        migrations.AddField(
            model_name='developercandidate',
            name='resume',
            field=models.FileField(default='resumes/default.pdf', help_text='Mandatory PDF Resume', upload_to='resumes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyclient',
            name='required_tech',
            field=models.CharField(help_text='Comma-separated required skills', max_length=255),
        ),
        migrations.AlterField(
            model_name='developercandidate',
            name='skills',
            field=models.TextField(help_text='Extracted or manual skills (Comma-separated)'),
        ),
        migrations.AlterField(
            model_name='developercandidate',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('On-Hold', 'On-Hold'), ('Rejected', 'Rejected')], default='Applied', max_length=50),
        ),
    ]
