# Generated by Django 6.0.7 on 2026-07-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_companyclient_min_experience_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developercandidate',
            name='ats_score',
            field=models.FloatField(default=0.0, help_text='Automated ATS Resume Score'),
        ),
        migrations.AddField(
            model_name='developercandidate',
            name='status_history',
            field=models.TextField(blank=True, default='', help_text='Audit logs of status changes'),
        ),
        migrations.AlterField(
            model_name='developercandidate',
            name='email',
            field=models.EmailField(help_text='Used for duplicate check & automated emails', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='developercandidate',
            name='previous_companies',
            field=models.TextField(blank=True, help_text='Extracted/Comma-separated company names'),
        ),
        migrations.AlterField(
            model_name='developercandidate',
            name='skills',
            field=models.TextField(help_text='Auto-extracted or manual skills (Comma-separated)'),
        ),
    ]
